- docs/PULL_REQUEST_TEMPLATE.md
just added content to PR template
> fill in pr template

- package.json
- tailwind.config.js
[Provide a brief description of the changes in this pull request]
[If applicable, include a link to the related issue]
[Describe the tests that you can run to verify your changes. Provide instructions so we can reproduce.]
> added tailwind config

- package-lock.json
- package.json
- src/App.tsx
- src/pages/About/About.tsx
- src/pages/Account/Account.tsx
- src/pages/Account/Dashboard/Dashboard.tsx
- src/pages/Account/FAQs/FAQs.tsx
- src/pages/Account/Home/Home.tsx
- src/pages/Account/Profile/Profile.tsx
- src/pages/Account/Quiz/Quiz.tsx
- src/pages/Account/Sessions/Sessions.tsx
- src/pages/Account/Support/Support.tsx
- src/pages/Advisors/Advisors.tsx
- src/pages/Advisors/Bio/Bio.tsx
- src/pages/Booking/Booking.tsx
- src/pages/ContactUs/ContactUs.tsx
- src/pages/Corporate/Corporate.tsx
- src/pages/FAQs/FAQs.tsx
- src/pages/Home/Home.tsx
- src/pages/Login/Login.tsx
- src/pages/SignUp/SignUp.tsx
- src/routes/AppRoutes.tsx
- tailwind.config.js
I added skeletons for the following pages of our app:
- Home
- About
- Account (commonly referred to as dashboard)
- Dashboard
- Home
- FAQs
- Profile
- Quiz
- Sessions
- Support
-  Advisors (to allow for growth)
- Bio
- Booking
- ContactUs
- Corporate
- FAQs
- Login
- SignUp
I've also added `AppRoutes` and updated `App` to incorporate `AppRoutes`
Closes #37 
1. `npm install` to install `react-router-dom`
2. Run the server: `npm run dev`
3. You should see the following text on the homepage:
> $ We are Nisa Invest. We are here to sort out your finances! $
4. You can also update the `/login` or `/signup` endpoints. Update `Login.tsx` to the following:
> ```ts
> function Login() {
>	return (
>		<>
>			<p>Hello</p>
>		</>
>	);
>}
>
>export default Login;
> ```
5. Navigate to …
> added skeletons for the pages we need

- package-lock.json
- package.json
- src/App.tsx
- src/components/Footer/Footer.tsx
- src/components/ui/separator.tsx
- src/pages/Home/Home.tsx
- src/routes/AppRoutes.tsx
Built and added a footer component.
It has been added to App.tsx so it appears on every page. 
Added routing for links to the pages that currently exist.
IG and LI Icons are currenlty placeholders, to be added later.
closes #8 
``npm install`` and ``npm run dev`` then check pages and play around, footer should be visible.
> build and add footer

- .storybook/main.ts
- src/components/SignUpForm/SignUpForm.tsx
- src/components/ui/radio-group.tsx
- src/pages/SignUp/SignUp.tsx
I've created a SignUpForm component and SignUp page. You can view this at `/signup`.
I tried to add a variable `defaultReason` to avoid hard-coding a default value, in case the reasons change in the future but had some type errors so have commented this out for now.
Closes #27
Run `npm install` > `npm run dev` and go to `/signup` to see the form in action.
> created signup form

- package-lock.json
- package.json
- src/components/Calendly/Calendly.tsx
- src/pages/Booking/Booking.tsx
- src/pages/Home/Home.tsx
- src/routes/AppRoutes.tsx
Embedded the Calendly widget into the Booking Page.
I have used react-calendly library to create a Calendly.tsx component
https://www.npmjs.com/package/react-calendly#basic-usage
closes #35 
``npm install`` and ``npm run dev``
then the  widget can be seen at ``/booking``
> Calendly embed

- src/components/ProfileCard/ProfileCard.tsx
- src/pages/Home/Home.tsx
I have created a profile card comopnent to hold profile of advisor and to direct to their page.
closes #19 
Just ``run npm dev`` and the example card is on the Home page.
Component can be used as below:
```html
<ProfileCard
name='Fahan Ibrahim Fashi'
position='Financial Advisor'
imageUrl='placeholder'
bioPage='fahan'
></ProfileCard>
```
> Component profile card

- package-lock.json
- package.json
- src/components/CarouselQuote/CarouselQuote.tsx
- src/components/CarouselTestimonial/CarouselTestimonial.tsx
- src/components/CarouselTestimonial/Testimonials.ts
- src/components/RatingStars/RatingStars.tsx
- src/components/TestimonialCard/TestimonialCard.tsx
- src/components/ui/carousel.tsx
- src/pages/Home/Home.tsx
Added following components:
- review starts (not used but kept for the future in case needed)
- TestimonyCard
- Carousel (from Shadcn)
- CarouselTestimony - utilising Shadcn carousel to create carousel with testimony cards
Moreover new library ```embla-carousel-autoplay``` has been installed
I've also added the new carousel to ``Home`` and style a bit to organise layout.
Changed export name of quote carousel to ``CarouselQuote`` to avoid confusion and conflict with other carousel types
Carousel data is taken from ``testimonies.ts`` file.
closes #13 
closes #14 
``npm install`` > ``npm run dev`` > go to home and see
> Component reviews

- src/pages/Login/Login.tsx
Added a signup redirect link below the login form.
npm run dev and go to /login to see changes
> add signup link to the login form

- src/utils/dataTypes.tsx
- src/utils/fetchData.tsx
I have added a generic function `useFetch( )`we can use everytime we need to fetch data.
inside the brackets you put the url which will give you the data you want. 
e.g. ` https://nisa-invest-tfb-be.vercel.app/users/all` will return all our user data.
Good thing is the data is stored in a state variable called `data` - so no more ASYNC calls! :D
copy and paste this into `Home.tsx`
you should open the console and see the data + names printed at the bottom of the page
```typescript
import CarouselQuote from '@/components/CarouselQuote/CarouselQuote';
import { quotes } from '@/components/CarouselQuote/data';
import { CarouselTestimonial } from '@/components/CarouselTestimonial/CarouselTestimonial';
import { testimonials } from '@/components/CarouselTestimonial/Testimonials';
import { …
```
> Fetch function

- src/components/NavBar/MobileNavItems.tsx
- src/components/NavBar/NavBar.tsx
- src/components/NavBar/NavItems.tsx
I've set the position: fixed for nav bar so it moves with scroll.
Closes #69
1. Run `npm install`
2. Run `npm run dev`
3. Navigate to http://localhost:5173 and scroll
4. The nav bar will cover some of the content. To fix this add the following className to the container of your main content: `pt-28`.
5. Check again and it should look perfect!
> setting position fixed for nav bar

- src/components/SignUpForm/SignUpForm.tsx
- src/utils/dataTypes.tsx
you can post data to back end on the sign up form
it is  missing 
- acknowledgement the form has been submitted
how to test:
fill the form and look at db in supabase (I will show you)
> POST request with sign up form

- src/components/FAQsAccordion/FAQsAccordion.tsx
- src/components/FAQsAccordion/faqsData.ts
- src/components/ui/accordion.tsx
Fahan's provided content so I populated the FAQs.
Run the app and view the shiny new questions and answers!
> populated faqs with real content

- src/components/SignUpForm/SignUpForm.tsx
Fixed build errors due to inconsistent names.
Run `npm run build` and it should work!
> Fix build error

- package-lock.json
- package.json
- src/components/ContactUsForm/ContactUsForm.tsx
- src/components/Dialog/Dialog.tsx
- src/components/ui/alert-dialog.tsx
- src/components/ui/dialog.tsx
- src/pages/Quiz/Quiz.tsx
when you complete the form, and submit the dialog will automatically open and let you know the request was successful!
how to test
click on to` book a demo ` button
fillout the form
see the beauty
when you close the dialog, the form will reset to default blank.
> created dialog 

- src/components/MyProfile/MyProfile.tsx
- src/pages/Account/Dashboard/Dashboard.tsx
Added a MyProfile section to dashboard
This contains user details fetched based on ID
as well as dialog box to edit details.
Details can be updated and will be saved in the database.
[If applicable, include a link to the related issue]
1. go to ``/dashboard`` and navigate to ``My profile `` tab
2. click ``edit profile `` button.
3. change any details and click ``save details``
4. Be mindblown
> My Profile - Dashboard

- src/pages/Account/Dashboard/Dashboard.tsx
Added an FAQs tab to the dashboard. This will cause a merge conflict with my `dashboard-home` PR, so please merge that first and I'll sort the conflict before we merge this one.
Navigate to FAQs on dashboard and witness the magic!
> added faqs to dashboard

- src/components/Dashboard/Dashboard.tsx
Corrected  title of the first section to ``Alhamdulillah...```
> correct title spelling

- src/components/NavBar/NavItems.tsx
Added a link to the nav bar that directs users to the quiz.
Hover over 'Knowledge Hub' on the nav bar and click the link for quiz!
> added link to nav bar

- src/AuthContext.tsx
fixed build error due to userId in AuthContext
> commented out errors

- src/components/Quiz/Quiz.styles.css
CSS for quiz was turning all buttons orange when focused.
> fixed css turning active buttons orange

- .github/workflows/deploy.yml
- README.md
- src/supabaseClient.ts
- vite.config.ts
not sure how to test if adding this client will work deployment.. @AlexVOiceover 
not sure if I have to import ` import { supabase } from './supabaseClient' ` on files that require supabase. 
Hopefully this will fix the deployment issue and we can pass the link to Fahan soon.
> added supabase client on front and and update ReadMe

- src/lib/auth.ts
getCurrentUser retruns a structure that contains both public and private user's data:
```
{
authUser: {
id: string,
email: string,
// ... other properties from Supabase auth.users table
},
publicUser: {
id: number,
auth_id: string,
first_name: string,
last_name: string,
// ... other properties from your public users table
}
}
```
> Update get current user
